// resources/js/pages/auth/otpz-verify.tsx
import { Head, useForm } from '@inertiajs/react';
import { LoaderCircle } from 'lucide-react';
import { FormEventHandler, useEffect, useState } from 'react';

import InputError from '@/components/input-error';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { index } from '@/routes/otpz';
import AuthLayout from '@/layouts/auth-layout';

interface LoginForm {
    code: string;
}

interface LoginProps {
    status?: string;
    id: string;
    email: string;
    url: string;
}

export default function Login({ status, id, email, url }: LoginProps) {
    const { data, setData, post, processing, errors, reset } = useForm<LoginForm>({
        code: '',
    });
    const [displayValue, setDisplayValue] = useState('');

    // Format the input value with a dash
    const formatValue = (value: string): string => {
        // Remove any non-alphanumeric characters
        const alphanumeric = value.replace(/[^a-zA-Z0-9]/g, '');

        // Format with dash if length > 5
        if (alphanumeric.length <= 5) {
            return alphanumeric;
        } else {
            const firstPart = alphanumeric.substring(0, 5);
            const secondPart = alphanumeric.substring(5, 10);
            return `${firstPart}-${secondPart}`;
        }
    };

    // Handler for input changes
    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const inputValue = e.target.value;

        // Process the input value
        const formattedValue = formatValue(inputValue);
        setDisplayValue(formattedValue);

        // Store the raw value (without dash) in form data
        setData('code', formattedValue.replace('-', ''));
    };

    // Update display value when data.code changes (for reset functionality)
    useEffect(() => {
        if (data.code === '') {
            setDisplayValue('');
        }
    }, [data.code]);

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post(url, {
            onFinish: () => {
                reset('code');
                setDisplayValue('');
            },
        });
    };

    return (
        <AuthLayout title="Use your code to login" description={`Enter the login code that was sent to ${email} Note that the code is case insensitive.`}>
            <Head title="Log in" />

            <form className="flex flex-col gap-6" onSubmit={submit}>
                <div className="grid gap-6">
                    <div className="grid gap-2">
                        <Label htmlFor="code">Login Code</Label>
                        <Input
                            className="text-center uppercase placeholder:lowercase"
                            id="code"
                            type="text"
                            required
                            autoFocus
                            tabIndex={1}
                            maxLength={11} // 10 chars + 1 dash
                            autoComplete="off"
                            value={displayValue}
                            onChange={handleInputChange}
                            placeholder="xxxxx-xxxxx"
                        />
                        <InputError message={errors.code} />
                    </div>

                    <Button type="submit" className="mt-4 w-full" tabIndex={4} disabled={processing}>
                        {processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
                        Submit Code
                    </Button>
                </div>

                <div className="text-muted-foreground text-center text-sm">
                    Didn't receive it?{' '}
                    <TextLink href={index.url()} tabIndex={5}>
                        Request a new code
                    </TextLink>
                </div>
            </form>

            {status && <div className="mb-4 text-center text-sm font-medium text-green-600">{status}</div>}
        </AuthLayout>
    );
}

// resources/js/pages/auth/OtpzVerify.vue
<script setup lang="ts">
import InputError from '@/components/InputError.vue';
import TextLink from '@/components/TextLink.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthBase from '@/layouts/AuthLayout.vue';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { LoaderCircle } from 'lucide-vue-next';
import { watch } from 'vue';
import { index } from '@/routes/otpz';

defineProps<{
    status?: string;
    email: string;
    url: string;
}>();

const page = usePage();
const email = page.props.email;
const url = page.props.url;

const form = useForm({
    code: '',
});


watch(
    () => form.code,
    (newVal) => {
        // Remove any non-alphanumeric characters
        let cleaned = newVal.replace(/[^a-zA-Z0-9]/g, '');

        // Enforce uppercase
        cleaned = cleaned.toUpperCase();

        // Limit to 10 alphanumeric characters
        cleaned = cleaned.slice(0, 10);

        // Insert dash after 5 characters (if there are more than 5)
        if (cleaned.length > 5) {
            cleaned = cleaned.slice(0, 5) + '-' + cleaned.slice(5);
        }

        // Update form.code only if it differs from what the user typed
        if (cleaned !== newVal) {
            form.code = cleaned;
        }
    }
);

const submit = () => {
    form.post(url);
};
</script>

<template>
    <AuthBase
        title="Use your code to login"
        :description="`Enter the login code that was sent to ${email} Note that the code is case insensitive.`"
    >
        <Head title="Enter Code" />

        <div v-if="status" class="mb-4 text-center text-sm font-medium text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit" class="flex flex-col gap-6">
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label for="code">Login Code</Label>
                    <Input
                        id="code"
                        type="text"
                        required
                        autofocus
                        :tabindex="1"
                        :maxlength="11"
                        autocomplete="off"
                        v-model="form.code"
                        placeholder="xxxxx-xxxxx"
                        class="text-center uppercase placeholder:lowercase"
                    />
                    <InputError :message="form.errors.code" />
                </div>

                <Button type="submit" class="mt-4 w-full" :tabindex="4" :disabled="form.processing">
                    <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
                    Submit Code
                </Button>
            </div>

            <div class="text-center text-sm text-muted-foreground">
                Didn't receive it?
                <TextLink :href="index.url()" :tabindex="5">Request a new code</TextLink>
            </div>
        </form>
    </AuthBase>
</template>
